name: Process KIP Submissions

permissions:
  contents: write

on:
  pull_request:
    branches:
      - master
    types: [closed]

jobs:
  check-and-update:
    if: github.event.pull_request.merged == true && startsWith(github.head_ref, 'submission/')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Fetch all history for all branches and tags

      - name: Check for KIP deletions
        uses: ./.github/workflows/checks.yaml
      
      - name: Update README
        run: |
          echo 'Updating README with new KIP entries...'
          python .github/scripts/update_master.py

      - name: Push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git commit -m "Update README with new KIP entries"
          git push